name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # or your preferred Node.js version

      - name: Install dependencies
        run: npm i && npm install vite -g # or yarn install if you use Yarn

      - name: Build with Vite
        run: npm run build # or yarn build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Vite's default build output directory is 'dist'
          branch: main
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add .nojekyll file (Optional - if needed for SPAs)
        run: touch ./dist/.nojekyll
        if: ${{ env.BUILD_PATH == 'dist' }} # Only create if the build path is 'dist'
